In [160]:
print("MultiLinear Regression")

MultiLinear Regression


In [161]:
# Formula 
# price = m1 * area + m2 * bedroom + m3 * age + b // ( y = (M1 * X1) + (M2 * X2) + (M3 * X3) + b )
# area,bedroom,age are independent variable
# price is a dependent variable
# m1,m2,m3 are coefficient and b is an intercept


In [162]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [163]:
df = pd.read_csv("MultiLinear Regression.csv")
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [164]:
# filling the missing value (filling the NaN by taking the medain of the dataColumn(bedroom median))
df.bedroom.median() #calculating the median of the column bedroom

3.5

In [165]:
# To get only integer value use math module math.floor
import math  # import the library for floor function
median_bedroom = math.floor(df.bedroom.median()) #floor function
median_bedroom

3

In [166]:
# syntex : df.cloumName_which_we_Want_to_fill = df.cloumName.fillna(value_to_be_filled)
df.bedroom = df.bedroom.fillna(median_bedroom) #filling the missing value with median value
# first we have the data set with one missing value, so we took median of that missing value column and fill the missing value with median.
df.bedroom
# Now we have the data set with no missing value

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedroom, dtype: float64

In [167]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [168]:
reg = linear_model.LinearRegression() #creating the linear regression module
reg.fit(df[['area','bedroom','age']],df.price) #fit() is a method we use to train the data set, independent variable are written inside 2D in double
# (i,e  area, bedroom, age) are independent variable , price is a dependent variable
# we train independent variable (i,e  area, bedroom, age) and predict the dependent variable(i,e price)

LinearRegression()

In [169]:
reg.coef_ # M1, M2, M3

array([   137.25, -26025.  ,  -6825.  ])

In [170]:
reg.intercept_# b

383724.9999999998

In [171]:
#predicting the room with 3000 sq ft, bedroom 3. and 40 years old 
reg.predict([[3000,3,40]])

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [172]:
# ( y = (M1 * X1) + (M2 * X2) + (M3 * X3) + b )
y = 137.25 * 3000 + -26025 * 3 + -6825* 40 + 383724.9999999998 
y
# we get the same value as we get from the predict method(rounOff value we get here using formula)


444399.9999999998

In [173]:
#predicting the room with 2500 sq ft, bedroom 4. and 5 years old 
reg.predict([[2500,4,5]])

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [174]:
#Exercise
# predict 2 yr of experiences, 9 test score, 6 interview score
# predict 12 yr of experiences, 10 test score, 10 interview score 

import pandas as pd
import numpy as np
from sklearn import linear_model

df = pd.read_csv("MultiLinear Regression(Exercise).csv")
df

experience  test_score(out of 10)  interview_score(out 0f 10)  salary($
0        NaN                    8.0                           9     50000
1        NaN                    8.0                           6     45000
2       five                    6.0                           7     60000
3        two                   10.0                          10     65000
4      seven                    9.0                           6     70000
5      three                    7.0                          10     62000
6        ten                    NaN                           7     72000
7     eleven                    7.0                           8     80000

In [175]:
from word2number import w2n
# asuming experience as zero 


# syntax : data_frame.column_name = data_frame.column_name.apply(w2n.word_to_num)
df['experience'] = df['experience'].fillna('zero')
df.experience = df.experience.apply(w2n.word_to_num)

# converting the words to number because regression is only for numbers
df

experience  test_score(out of 10)  interview_score(out 0f 10)  salary($
0           0                    8.0                           9     50000
1           0                    8.0                           6     45000
2           5                    6.0                           7     60000
3           2                   10.0                          10     65000
4           7                    9.0                           6     70000
5           3                    7.0                          10     62000
6          10                    NaN                           7     72000
7          11                    7.0                           8     80000

In [176]:
#changing the column name

df.rename(columns={"test_score(out of 10)":"test_score"},inplace=True)
df.rename(columns={"interview_score(out 0f 10)":"interview_score"},inplace=True)
df.rename(columns={"salary($":"salary"},inplace=True)

df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [177]:
import math
median_testScore = math.floor(df.test_score.median())
median_testScore

8

In [178]:
df.test_score = df.test_score.fillna(median_testScore)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [179]:
reg = linear_model.LinearRegression()
reg.fit(df[["experience","test_score","interview_score"]],df.salary)

LinearRegression()

In [181]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [182]:
reg.intercept_

17737.263464337688

In [183]:
reg.predict([[2,9,6]])

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [184]:
reg.predict([[12,10,10]])

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])